In [ ]:
#install dependencies

In [1]:
!pip install tensorflow tensorflow-gpu pandas matplotlib sklearn

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Lenovo\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-fto9t6sh\\tensorflow-gpu_9df0361685e34be38e6558c3dee4d73e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-fto9t6sh\\tensorflow-gpu_9df0361685e34be38e6558c3dee4d73e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Lenovo\AppData\Local\Temp\pip-wheel-vjr6dcen'
       cwd: C:\Users\Lenovo\AppData\Local\Temp\pip-install-fto9t6sh\tensorflow-gpu_9df0361685e34be38e6558c3dee4d73e\
  Complete output (17 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "

  Running setup.py clean for tensorflow-gpu
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2959 sha256=627fa3206b33a0a1bd026bcb509eedfaa0d8c560d561e279c4c7ff3fbcfa5e0d
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\f8\e0\3d\9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn
Failed to build tensorflow-gpu
    Running setup.py install for tensorflow-gpu: started
    Running setup.py install for tensorflow-gpu: finished with status 'error'


In [1]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
df=pd.read_csv(os.path.join( 'jigsaw-toxic-comment-classification-challenge','train.csv','train.csv' ))

In [3]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [4]:
df.iloc[5]['comment_text']

'"\n\nCongratulations from me as well, use the tools well. \xa0· talk "'

In [5]:
#preprocess

In [6]:
from tensorflow.keras.layers import TextVectorization

In [7]:
x=df['comment_text']
y=df[df.columns[2:]].values

In [8]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [9]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [10]:
MAX_FEATURES=200000 # no of words in the vocab

In [11]:
vectorizer=TextVectorization(max_tokens=MAX_FEATURES,
                            output_sequence_length=1800,
                            output_mode='int')

In [12]:
vectorizer.adapt(x.values) #training

In [13]:
vectorized_text=vectorizer(x.values)

In [14]:
len(x)

159571

In [15]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  643,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2506, ...,     0,     0,     0],
       [  425,   440,    70, ...,     0,     0,     0],
       ...,
       [32141,  7329,   383, ...,     0,     0,     0],
       [    5,    12,   533, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [16]:
#MCSHBAP-map,cache,shuffle,batch,prefetch,from_tensor_Slices,list_file
dataset=tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset=dataset.cache()
dataset=dataset.shuffle(160000)
dataset=dataset.batch(16)
dataset=dataset.prefetch(8)#helps bottleneck

In [17]:
batch_x,batch_y= dataset.as_numpy_iterator().next()

In [18]:
batch_y.shape

(16, 6)

In [19]:
batch_x

array([[    6,  1040,    13, ...,     0,     0,     0],
       [ 1066,  1175,   168, ...,     0,     0,     0],
       [ 1967,  1114,     4, ...,     0,     0,     0],
       ...,
       [  181, 65414,     9, ...,     0,     0,     0],
       [   46,   167,    23, ...,     0,     0,     0],
       [   94,    13,  1523, ...,     0,     0,     0]], dtype=int64)

In [20]:
batch_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [21]:
train=dataset.take(int(len(dataset)*.7))
val=dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test=dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [22]:
train_generator=train.as_numpy_iterator()

In [23]:
train_generator.next()

(array([[ 136,  180,    6, ...,    0,    0,    0],
        [ 311,  103,   22, ...,    0,    0,    0],
        [4103, 1818,   70, ...,    0,    0,    0],
        ...,
        [  66,    9,   40, ...,    0,    0,    0],
        [ 175,    6,  100, ...,    0,    0,    0],
        [ 170,  218,   17, ...,    0,    0,    0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

In [24]:
#building neural network
#create sequential network

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dropout,Bidirectional,Dense,Embedding

In [26]:
model =Sequential()
#Create the embedding layer
model.add(Embedding(MAX_FEATURES+1,32))
model.add(Bidirectional(LSTM(32,activation='tanh')))
#Feature extractor fully connected layers
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
#Final layer
model.add(Dense(6,activation='sigmoid'))

In [27]:
model.compile(loss='BinaryCrossentropy',optimizer='Adam')

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [29]:
history= model.fit(train,epochs=1,validation_data=val)

6981/6981 [==============================] - 9433s 1s/step - loss: 0.0618 - val_loss: 0.0465


In [30]:
history.history

{'loss': [0.061847057193517685], 'val_loss': [0.04648042842745781]}

In [31]:
from matplotlib import pyplot as plt

In [31]:
#make predictions

In [35]:
input_text=vectorizer('You freaking suck! I am going to hit you. ')

In [33]:
batch=test.as_numpy_iterator().next()

In [34]:
batch_x,batch_y=test.as_numpy_iterator().next()

In [35]:
(model.predict(batch_x)>0.5).astype(int)

1/1 [==============================] - 1s 941ms/step


array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [36]:
res=model.predict(batch_x)

1/1 [==============================] - 0s 117ms/step


In [37]:
res.shape

(16, 6)

In [38]:
res

array([[5.79323992e-02, 1.64722849e-04, 6.31269254e-03, 1.17318786e-03,
        1.06050298e-02, 5.30141965e-03],
       [7.37030506e-01, 2.12667473e-02, 3.43727589e-01, 2.76873056e-02,
        3.22112054e-01, 8.30162540e-02],
       [3.55061020e-05, 8.69722960e-10, 7.16910961e-07, 9.53326307e-08,
        2.57754027e-06, 2.78410039e-06],
       [1.47978222e-04, 1.25650033e-08, 4.57951091e-06, 7.81336041e-07,
        1.41708479e-05, 1.43477910e-05],
       [2.98040795e-05, 6.78335166e-10, 5.87089346e-07, 7.74165372e-08,
        2.14189663e-06, 2.29221314e-06],
       [2.31415746e-04, 2.98342151e-08, 8.18866556e-06, 1.52337634e-06,
        2.42593505e-05, 2.37554341e-05],
       [8.12791754e-04, 2.95938662e-07, 4.02047335e-05, 9.29897578e-06,
        1.05492727e-04, 9.71324480e-05],
       [6.40561455e-04, 1.64217482e-07, 2.84122380e-05, 5.91027310e-06,
        7.63847274e-05, 7.25741338e-05],
       [5.94758778e-04, 1.37728790e-07, 2.51621113e-05, 5.15920146e-06,
        6.82201207e-05, 

In [39]:
(res>0.5).astype(int)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [40]:
#evaluate model

In [41]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [42]:
pre=Precision()
re=Recall()
acc=CategoricalAccuracy()

In [43]:
for batch in test.as_numpy_iterator():
    #unpack the batch
    x_true,y_true=batch
    #make a prediction
    yhat=model.predict(x_true)
    
    y_true=y_true.flatten()
    yhat=yhat.flatten()
    pre.update_state(y_true,yhat)
    re.update_state(y_true,yhat)
    acc.update_state(y_true,yhat)

1/1 [==============================] - 0s 114ms/step


1/1 [==============================] - 0s 145ms/step


1/1 [==============================] - 0s 109ms/step


1/1 [==============================] - 0s 100ms/step


In [44]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')


Precision: 0.7869300842285156, Recall:0.7367672324180603, Accuracy:0.5005015134811401


In [45]:
#test ad gradient

In [82]:
!pip install gradio jinja2

In [93]:
pip install --upgrade pydantic

Note: you may need to restart the kernel to use updated packages.


In [96]:
pip install --upgrade fastapi


In [99]:
pip install --upgrade gradio


Note: you may need to restart the kernel to use updated packages.


In [46]:
import gradio as gr

In [47]:
model.save('toxicity.h5')

In [48]:
model= tf.keras.models.load_model('toxicity.h5')

In [49]:
input_str= vectorizer('hey I freaken hate you')

In [50]:
res= model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 1s 686ms/step


In [51]:
res

array([[0.87665236, 0.05166316, 0.56623024, 0.03089595, 0.4333183 ,
        0.10684945]], dtype=float32)

In [52]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [53]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

C:\Users\Lenovo\anaconda3\lib\site-packages\gradio\inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\Lenovo\anaconda3\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\Lenovo\anaconda3\lib\site-packages\gradio\deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)


In [54]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://fe1f92089a0d0e3432.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
1/1 [==============================] - 0s 78ms/step


1/1 [==============================] - 0s 67ms/step
